### ISSUE TITLE
End the call before connected.

### ISSUE THREAD

**Issue by jessicawang143143** [twilio/voice-quickstart-swift#64] opened 2017-09-04 04:34 UTC
I have a feature in my app: end the call before connected(the scenario is like the user dials a wrong number and wants to hang up immediately.). I find all the sample code twilio give out are disable the hang up button until the call connected. But I got a warning these days: WARN TVOCall] disconnect only works when the call state is "TVOCallStateConnected" or "TVOCallStateConnecting".Does this mean I can end the call before connected? When I do this I get some problems: 
1. Make the call, end the call before it connected, the call has possibilities to go out.
2. Make the call, end the call before it connected, make another call, the second call fails.
3. Make the call, end the call before it connected, make another call, repeat these steps several times, the call loses signal

#### Expected Behavior

These calls can be disconnected properly and not prevent make another call.

#### Logs

[Logs.pdf](https://github.com/twilio/voice-quickstart-swift/files/1273666/Logs.pdf)

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

Twilio version:2.0.0-beta14 (August 15, 2017)

#### Xcode

 8.3.3

#### iOS Version

10.3.3

#### iOS Device

 iPhone se , iphone 6

**Comment by bchen-twilio** [comment] 2017-09-07 00:45
Hi @jessicawang143143 

Thanks for reporting the issue.
We do have integration test cases to cover such use case (disconnect while the call is connecting) but it seems there is still some edge cases that need to be fixed based on your description and log. We've created a ticket CLIENT-3820 for tracking this issue in the future sprints.

Will keep you posted.
-bobie

**Comment by bchen-twilio** [comment] 2017-10-13 20:51
Hi @jessicawang143143 

Sorry for my delay in responding back to you with the updates.
We've included a fix in beta17/18 to address the issue that calls still get connected when `[TVOCall disconnect]` is called, especially when the call is still in the `TVOCallStateConnecting` state.
It'd be great if you can update to the latest version of the SDK and see if the issue is fixed.
Thanks!

-bobie

**Comment by bchen-twilio** [comment] 2018-01-10 00:55
Closing this ticket since we've fixed the early-disconnect issue. Please feel free to open a new issue.
Thanks.

**Closed by bchen-twilio** 2018-01-10 00:55 UTC

**Comment by ramohanreddy** [comment] 2019-02-15 10:20
Hi @bchen-twilio 
I got incoming call from  client but when client disconnect the call still my call is not diconnected still it was connected .
I am using iPhone 6s (IOS 11.3)

Thanks

**Comment by bchen-twilio** [comment] 2019-02-15 17:11
Hi @ramohanreddy 

On the callee client you can use the `[TVOCallInvite reject]` method to reject the call or use the `[TVOCall disconnect]` method to disconnect after the call is accepted and connected, that way the caller client will get a proper `callDidDisconnect:` delegate callback.

Thanks
-bobie
