### ISSUE TITLE
No in-call audio on consecutive calls

### ISSUE THREAD

**Issue by lottadot** [twilio/voice-quickstart-swift#39] opened 2017-06-06 19:10 UTC
Using 2.0.0 b9 SDK, iOS 10.3.2 iPhone6 and a iOS 10.3.1 iPhone6S, Xcode 8.3.2.

3 calls placed consecutively.
Same direction each time.
Sometimes the second, third or forth calls will fail w/ no audio. 
(Sometimes I've had 4 in row connect and have audio just fine too; there doesn't seem to be a pattern here).
But the audio in the calls seemingly should not fail this often, with a beta9 sdk (imho).
The connections always seem to connect fine, regardless of audio.

In the logs I'll attach to this ticket, the third call had no audio. The first two were perfect. A little crackly in Audio, but I could hear audio from both sides.

I put the Twilio SDK into verbose mode. I've got similar logging from our own code that manages the twilio SDK. Sorry, you'll have to skim through that as well.
[twilio-no-audio-logs.zip](https://github.com/twilio/voice-quickstart-swift/files/1056123/twilio-no-audio-logs.zip)

**Comment by bchen-twilio** [comment] 2017-06-06 19:45
Thanks for the log and detailed description of the issue @lottadot!
I'll take a look at the log and keep you updated once I found anything.

-bobie

**Comment by bchen-twilio** [comment] 2017-06-06 20:15
Hi @lottadot 

I've noticed that in the log your mobile client is using wifi connections and the network seems to be behind the firewall (maybe just some basic firewall config). I don't have the conclusion yet but just would like to see if the no-audio issue still happens in your application if the device is using cellular data connections.

Trying in my environment as well while waiting for the help from the backend service team to see if they see anything wrong with the signaling.

**Comment by lottadot** [comment] 2017-06-06 20:29
Unfortunately, I don't have two cellular devices that I can use. Just one. Let me see if I can bribe someone hear to let me hack on their phone for a bit.

**Comment by bchen-twilio** [comment] 2017-06-06 20:31
One, for the incoming call receiver, should be good enough :)

**Comment by bchen-twilio** [comment] 2017-06-06 20:46
Hi @lottadot 

If it's not too much trouble for you, could you also try using the callkit swift quickstart in your original wifi environment? I've run it for about 30 incoming calls with 2 different wifis and cellular data but so far I am always able to hear audio.

**Comment by lottadot** [comment] 2017-06-07 15:44
Attached is the debug log of the SwiftVoiceCallKitQuickstart
[voice-quickstart-swift-Issue-39-VOIP-Outbound-to-cell-no-audio.txt](https://github.com/twilio/voice-quickstart-swift/files/1058565/voice-quickstart-swift-Issue-39-VOIP-Outbound-to-cell-no-audio.txt)
 app:

1. Using my own server URL
2. Using my own bundle identifier 

Ran in Xcode 8.3.2, on iPhone6 10.3, and dialed to my cell. There was no audio.

Two separate runs were made. This log is one of them. Both calls had no audio.

**Comment by lottadot** [comment] 2017-06-08 15:13
Here are some more log snippets. Same code, same devices, not on our corporate wifi, instead on a cellular hot spot's wifi. First 4 calls were fine, 5th call, no audio. We were doing voip to voip calls (i.e. `resp.dial(callerId=request.form['From']).client("BBB")`

[voice-quickstart-swift-issue-39-call-logs-cellular-hotspot.zip](https://github.com/twilio/voice-quickstart-swift/files/1061449/voice-quickstart-swift-issue-39-call-logs-cellular-hotspot.zip)

**Comment by lottadot** [comment] 2017-06-08 15:18
Here are some additional log snippets. Same code, same hotspot wifi, but instead of voip to voip, we did voip to cellular (i.e. `resp.dial(callerId="+1614XXXYYYY").number("+1614AAABBBB")` 


[voice-quickstart-swift-issue-39-call-logs-cellular-hotspot-to-cellular.zip](https://github.com/twilio/voice-quickstart-swift/files/1061465/voice-quickstart-swift-issue-39-call-logs-cellular-hotspot-to-cellular.zip)

**Comment by bchen-twilio** [comment] 2017-06-09 16:59
Hi @lottadot 

Thanks for trying different combinations and providing us the logs 👍 
Didn't realize that it was you in the email thread.

While I was trying to figure out #31 I found that, as in my last comment, if the subsequent calls are made **before the `provider:didDeactivatedAudioSession:` callback is called**, then the no-audio issue will happen.

While we are figuring out the best way to solve this, it would be great if you and the team can help confirm my theory.

Btw, it doesn't matter if the call is between two wifi devices or one wifi the other cellular - the Twilio Media Server is always in the middle relaying media. The reason I was asking you to try to reproduce cellular is that I want to make sure it's not the private IP address issued by the wifi access-point that is causing the Media Server trouble.

Let me know
-bboie

**Comment by lottadot** [comment] 2017-06-16 14:11
@bchen-twilio , I believe that your thoughts on ordering of the messages send before/after `provider:didDeactivatedAudioSession:` are spot-on.

From a successful Inbound call:
```
2017-06-08 11:06:48.639132 SwiftVoiceCallKitQuickstart[809:546563] provider:performEndCallAction:
2017-06-08 11:06:48.639301 SwiftVoiceCallKitQuickstart[809:546563] [VERBOSE TwilioVoice] Inside stopAudioDevice, stopping audio device.
2017-06-08 11:06:48.655105 SwiftVoiceCallKitQuickstart[809:546939] PJSIP(5): tsx0x1038dd4a8  Timeout timer event
2017-06-08 11:06:48.690132 SwiftVoiceCallKitQuickstart[809:546939] PJSIP(5): tsx0x1038dd4a8  .State changed from Terminated to Destroyed, event=TIMER
2017-06-08 11:06:48.690601 SwiftVoiceCallKitQuickstart[809:546939] PJSIP(5): tdta0x1038e0c0  ..Destroying txdata Response msg 200/BYE/cseq=1 (tdta0x1038e0c00)
2017-06-08 11:06:48.690685 SwiftVoiceCallKitQuickstart[809:546939] PJSIP(5): tsx0x1038dd4a8  Transaction destroyed!
2017-06-08 11:06:48.951151 SwiftVoiceCallKitQuickstart[809:546692] [DEBUG TVOEventPublisher] TwilioVoiceClient Endpoint-Analytic HTTP response - status: 200, error: (null)
2017-06-08 11:06:48.951421 SwiftVoiceCallKitQuickstart[809:546692] [VERBOSE TVOEventPublisher] Request sent
2017-06-08 11:06:48.958830 SwiftVoiceCallKitQuickstart[809:546809] [DEBUG TVOEventPublisher] TwilioVoiceClient Endpoint-Analytic HTTP response - status: 200, error: (null)
2017-06-08 11:06:48.959004 SwiftVoiceCallKitQuickstart[809:546809] [VERBOSE TVOEventPublisher] Request sent
2017-06-08 11:06:50.230036 SwiftVoiceCallKitQuickstart[809:546563] provider:didDeactivateAudioSession:
2017-06-08 11:06:51.623510 SwiftVoiceCallKitQuickstart[809:546939] PJSIP(4):    pjsua_aud.c  Closing sound device after idle for 3 second(s)
2017-06-08 11:06:51.630412 SwiftVoiceCallKitQuickstart[809:546939] PJSIP(4):    pjsua_aud.c  .Closing iPhone IO device sound playback device and iPhone IO device sound capture device
2017-06-08 11:06:51.632298 SwiftVoiceCallKitQuickstart[809:546939] PJSIP(4): coreaudio_dev.  .core audio stream stopped
```

From a subsequent successful Inbound call where *the next call attempt has no audio:
```
2017-06-08 11:09:00.830386 SwiftVoiceCallKitQuickstart[809:546563] provider:performEndCallAction:
2017-06-08 11:09:00.830569 SwiftVoiceCallKitQuickstart[809:546563] [VERBOSE TwilioVoice] Inside stopAudioDevice, stopping audio device.
2017-06-08 11:09:01.275265 SwiftVoiceCallKitQuickstart[809:548057] [DEBUG TVOEventPublisher] TwilioVoiceClient Endpoint-Analytic HTTP response - status: 200, error: (null)
2017-06-08 11:09:01.275438 SwiftVoiceCallKitQuickstart[809:548057] [VERBOSE TVOEventPublisher] Request sent
2017-06-08 11:09:01.276282 SwiftVoiceCallKitQuickstart[809:547874] [DEBUG TVOEventPublisher] TwilioVoiceClient Endpoint-Analytic HTTP response - status: 200, error: (null)
2017-06-08 11:09:01.276803 SwiftVoiceCallKitQuickstart[809:547874] [VERBOSE TVOEventPublisher] Request sent
2017-06-08 11:09:02.502181 SwiftVoiceCallKitQuickstart[809:546563] provider:didDeactivateAudioSession:
2017-06-08 11:09:03.796989 SwiftVoiceCallKitQuickstart[809:546939] PJSIP(4):    pjsua_aud.c  Closing sound device after idle for 3 second(s)
2017-06-08 11:09:03.803680 SwiftVoiceCallKitQuickstart[809:546939] PJSIP(4):    pjsua_aud.c  .Closing iPhone IO device sound playback device and iPhone IO device sound capture device
2017-06-08 11:09:03.804957 SwiftVoiceCallKitQuickstart[809:546939] PJSIP(4): coreaudio_dev.  .core audio stream stopped
2017-06-08 11:09:06.231101 SwiftVoiceCallKitQuickstart[809:546563] pushRegistry:didReceiveIncomingPushWithPayload:forType:
2017-06-08 11:09:06.233605 SwiftVoiceCallKitQuickstart[809:546563] [INFO TVOCall] Inside publishConenctionEvent:, event type: incoming
2017-06-08 11:09:06.236083 SwiftVoiceCallKitQuickstart[809:546563] [VERBOSE TVOCall] Inside publisherConnectionEvent:, sending incoming event
2017-06-08 11:09:06.236359 SwiftVoiceCallKitQuickstart[809:546563] [DEBUG TVOEventPublisher] Publishing event to Twilio Endpoint Analytics
2017-06-08 11:09:06.238317 SwiftVoiceCallKitQuickstart[809:546563] callInviteReceived:
2017-06-08 11:09:06.256862 SwiftVoiceCallKitQuickstart[809:546563] Incoming call successfully reported.
2017-06-08 11:09:06.257147 SwiftVoiceCallKitQuickstart[809:546563] [VERBOSE TwilioVoice] Inside configureAudioSession, preparing audio session.
2017-06-08 11:09:06.753762 SwiftVoiceCallKitQuickstart[809:547973] [DEBUG TVOEventPublisher] TwilioVoiceClient Endpoint-Analytic HTTP response - status: 200, error: (null)
2017-06-08 11:09:06.753890 SwiftVoiceCallKitQuickstart[809:547973] [VERBOSE TVOEventPublisher] Request sent
2017-06-08 11:09:07.854189 SwiftVoiceCallKitQuickstart[809:546563] provider:performEndCallAction:
2017-06-08 11:09:07.854473 SwiftVoiceCallKitQuickstart[809:546563] [VERBOSE TwilioVoice] Inside stopAudioDevice, stopping audio device.
2017-06-08 11:09:07.855093 SwiftVoiceCallKitQuickstart[809:546563] [DEBUG TVOCall] Inside reject, rejecting call from +16143502448.
2017-06-08 11:09:07.855338 SwiftVoiceCallKitQuickstart[809:546563] [DEBUG TVOCommandHandler] Inside postCommand:, received command of type TVORejectCallCommand
2017-06-08 11:09:07.855454 SwiftVoiceCallKitQuickstart[809:546563] [INFO TVOCall] Inside publishConenctionEvent:, event type: rejected-by-local
2017-06-08 11:09:07.856538 SwiftVoiceCallKitQuickstart[809:546563] [VERBOSE TVOCall] Inside publisherConnectionEvent:, sending rejected-by-local event
2017-06-08 11:09:07.856658 SwiftVoiceCallKitQuickstart[809:546563] [DEBUG TVOEventPublisher] Publishing event to Twilio Endpoint Analytics
2017-06-08 11:09:07.857316 SwiftVoiceCallKitQuickstart[809:546563] [VERBOSE TVOCall] handlePJSIPInviteStateDisconnected. Error: (null)
2017-06-08 11:09:07.859314 SwiftVoiceCallKitQuickstart[809:548057] [VERBOSE Twilio] Inside constructUri: Registration URL: sip:None@chunderm.gll.twilio.com;transport=tls
2017-06-08 11:09:07.870106 SwiftVoiceCallKitQuickstart[809:546563] [DEBUG TwilioVoice] Inside removeFromActiveCalls:, no matching active call for <TVOCall: 0x1700fde00>
2017-06-08 11:09:07.871073 SwiftVoiceCallKitQuickstart[809:548057] [INFO TVORejectCallCommand] Call URI: sip:None@chunderm.gll.twilio.com;transport=tls
2017-06-08 11:09:07.871216 SwiftVoiceCallKitQuickstart[809:546563] [DEBUG TVORTCMonitorThresholds] No thresholds specified. Default values will be applied.
2017-06-08 11:09:07.871479 SwiftVoiceCallKitQuickstart[809:548057] PJSIP(4):   pjsua_call.c !Making call with acc #0 to sip:None@chunderm.gll.twilio.com;transport=tls
```

The one difference that I’ve seen a few times is `TwilioVoiceClient Endpoint-Analytic HTTP response - status: 200, error: (null)`. I’m not sure what the means directly, nor the consequences of it?
Still, the second log snippet shows `provider:didDeactivateAudioSession` before the `callInviteReceived:`.


For the purposes of just creating a working demo, I did experiment with trying to address it by doing something like this:

```
	public func provider(_ provider: CXProvider, didDeactivate audioSession: AVAudioSession) {
		NSLog("VoipCoord:provider:didDeactivateAudioSession:")
		
//		// Sometimes if a call was dialed, and the other end accepts and then quickly ends the call, we'll be told `didDeactivateAudioSession` but we'll never receive a `callDidDisconnect` from Twilio itself.
//		let selector:Selector = #selector(wasCallLostButWeWereNotNotified(_:))
//		self.perform(selector, with: nil, afterDelay: 3.0)
	}
```

And in `wasCallLostButWeWereNotNotified` if there was a non-nil call then self.endCall(uuid: call.uuid) or remove or UI.

I’m not sure if such a hack really worked all that well. To be honest, if the `CXProviderDelegate CallKit Provider Delegate` doesn’t ever send the `didDeactivateAudioSession`, do we wait for X amount of seconds and then send the `AVAudioSession` an `setActive:false` ?

**Comment by bchen-twilio** [comment] 2017-06-16 20:52
Hi @lottadot 

Thanks for the log and experiment/feedback.
We've added a new method in the CallKitIntegration category of the TwilioVoice object. This method should be called on receiving the provider:didDeactivateAudioSession: callback from CallKit. This way it ensures some internal flags of SDK's audio stack are reset correctly so that subsequent calls have good audio.

We are still seeing some bizarre issues around this issue on iOS 11 beta, but once we have the sign-off from the QE team with good validation results we will release the new beta.

Thank

**Comment by lottadot** [comment] 2017-06-26 14:35
I see 2.0.0-beta11 mentioned in the changeling https://www.twilio.com/docs/api/voice-sdk/ios/changelog It mentions some change per Audio.

@bchen-twilio is this the beta you are referring to in your previous comment?

We haven't tried anything Twilio-related w/ the iOS11 beta's. Though, if the 2.0.0-beta11 is thought to address the audio issue this ticket is about, I may cut a binary build with it generated by Xcode8 and another Xcode9 for our internal QA team here.

Thanks,
 Shane

**Comment by bchen-twilio** [comment] 2017-06-26 17:29
Hi @lottadot 

Yes, the fix included in beta11 is to address the no-audio issue for subsequent calls, but mainly for CallKit integration. With the newly added `audioSessionDeactivated` method, the SDK is able to shutdown and reset the audio device properly to ensure good audio for subsequent calls. Please make sure to use this method on receiving the `provider:didDeactivateAudioSession:` callback **before making/accept subsequent calls**.

We will keep improving the logic around this area to make sure the audio stack is bulletproof.
Thanks.
-bobie

**Comment by bchen-twilio** [comment] 2017-08-10 18:34
Hi @lottadot 

I am assuming with the latest beta of the iOS Voice SDK the no-audio issue no longer exists and am closing this ticket. Please feel free to re-open or create a new issue if you run into any trouble using the SDK.

Cheers,
-bobie

**Closed by bchen-twilio** 2017-08-10 18:34 UTC
