### ISSUE TITLE
Getting a 500 Server Error when calling

### ISSUE THREAD

**Issue by BayPhillips** [twilio/voice-quickstart-swift#35] opened 2017-06-04 14:40 UTC
Hey there,

I'm following the quickstart guide and we're running into a "Generic" error response from Twilio when making an outbound call:

```
Call failed with error: Error Domain=com.twilio.voice.error Code=31000 "Generic error (500)." UserInfo={NSLocalizedDescription=Generic error (500)., NSLocalizedFailureReason=Generic error.}
```

I then looked up the error `31000` which is just a generic error to which I should check the debugger. There doesn't seem to be any further logs/errors there though.

The verbose debugging also lends itself to an Internal Server Error. I'm happy to provide the full output + code to you guys in an email if that would help things out.

We're on the latest pod `TwilioVoice', '=2.0.0-beta9'` so I don't think I'm using anything out of date. Thanks for the help :)

**Comment by bchen-twilio** [comment] 2017-06-04 18:24
Hi @BayPhillips 

Sorry for the confusion. SIP 500 response code (Server Internal Error) usually could be caused to failure when Twilio Voice service tries to fetch the TwiML specified by the application-SID embedded in your access token.

It would be great if you could enable SDK logging by this:
```
  TwilioVoice.sharedInstance().logLevel = .verbose
```
and send us the log when you encounter the error. We would be happy to look into the log and see if we can find out anything that could also cause the error you are seeing.

Meanwhile you could also go to your [Programmable Voice dashboard](https://www.twilio.com/console/voice/dashboard) and see if you can find any errors/warnings at the upper-right corner. These real time errors/warnings may contain more details about the cause of the failure.

Let me know if this helps.
Thanks.
-bobie

**Comment by BayPhillips** [comment] 2017-06-05 03:11
Shot you an email @bchen-twilio, thank you for helping!

**Comment by bchen-twilio** [comment] 2017-06-07 18:10
Hi @BayPhillips 

Hope this finds you well.
Any luck trying to make all the call parameters strings?

**Comment by bchen-twilio** [comment] 2017-06-08 20:19
Hi @BayPhillips 

I am assuming hopefully with my suggestion you and the team are now able to make the calls through so I am closing this issue.
Please feel free to reopen if the same issue persists or open a new issue if you run into any issues in the future.

Thanks for choosing the Voice SDK.
-bobie

**Closed by bchen-twilio** 2017-06-08 20:19 UTC

**Comment by BayPhillips** [comment] 2017-06-09 02:37
Hey @bchen-twilio so sorry for the delay! Been hungup with all of the WWDC awesomeness :)

Yes, we've been able to move on with the changing the call params to all strings. Thank you for your help!

**Comment by bchen-twilio** [comment] 2017-06-09 04:20
Awesome @BayPhillips!
Yeah too bad one of our team member got luck to join the WWDC party this year or we can meet there and catch up.
👍 cheers.

**Comment by mindwards** [comment] 2017-08-17 00:17
I got the same error whenever the identity embedded on the authentication token contained an "@" sign. That identity ends up on the "From" field. Removed the "@" and everything worked.
