### ISSUE TITLE
Crash when app is slow (race condition?)

### ISSUE THREAD

**Issue by Speakus** [twilio/voice-quickstart-swift#90] opened 2018-01-02 19:44 UTC
### Description

Crash on call.

### Steps to Reproduce

0. use slow computer (slow simulator) computer with HDD should be good - in our case it was macmini 2014 8GB with HDD. Xcode 9.2.

1. `git clone git@github.com:WingTel/voice-quickstart-swift.git`
2. pod install
3. run simulator
4. feel AccessToken field
5. press button

#### Expected Behavior

no crash

#### Actual Behavior

crash!

![image](https://user-images.githubusercontent.com/849294/34497168-289d839e-f048-11e7-8e76-30a81163410b.png)

#### Reproduces How Often

100% for slow computer.

#### Logs

```
2018-01-02 14:30:17.747589-0500 SwiftVoiceCallKitQuickstart[38632:8423627] Twilio Voice Version: 2.0.0
2018-01-02 14:30:17.821229-0500 SwiftVoiceCallKitQuickstart[38632:8423627] [MC] Lazy loading NSBundle MobileCoreServices.framework
2018-01-02 14:30:17.822679-0500 SwiftVoiceCallKitQuickstart[38632:8423627] [MC] Loaded MobileCoreServices.framework
2018-01-02 14:30:17.882196-0500 SwiftVoiceCallKitQuickstart[38632:8423627] providerDidBegin
2018-01-02 14:30:17.883682-0500 SwiftVoiceCallKitQuickstart[38632:8423627] [VERBOSE TwilioVoice] Application did become active
2018-01-02 14:30:17.883868-0500 SwiftVoiceCallKitQuickstart[38632:8423627] [DEBUG TVOReachability] Reachability Flag Status: -R ------- networkStatusForFlags
2018-01-02 14:31:34.504610-0500 SwiftVoiceCallKitQuickstart[38632:8423627] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /Users/wing/Library/Developer/CoreSimulator/Devices/67E04DEB-C67F-4D00-AA55-EFB1F1879B79/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2018-01-02 14:31:34.505071-0500 SwiftVoiceCallKitQuickstart[38632:8423627] [MC] Reading from private effective user settings.
2018-01-02 14:31:47.903370-0500 SwiftVoiceCallKitQuickstart[38632:8425111] StartCallAction transaction request successful
2018-01-02 14:31:47.908415-0500 SwiftVoiceCallKitQuickstart[38632:8423627] provider:performStartCallAction:
2018-01-02 14:31:47.908970-0500 SwiftVoiceCallKitQuickstart[38632:8423627] [VERBOSE TwilioVoice] configureAudioSession.
2018-01-02 14:31:47.909345-0500 SwiftVoiceCallKitQuickstart[38632:8423627] [VERBOSE TwilioVoice] Disable audio.
2018-01-02 14:31:47.945549-0500 SwiftVoiceCallKitQuickstart[38632:8423627] [DEBUG Twilio] init Twilio user agent.
WARNING: no real random source present!
2018-01-02 14:31:48.162429-0500 SwiftVoiceCallKitQuickstart[38632:8423627] [VERBOSE Twilio] Inside setCodecPriorities:, codec: speex/16000/1 -> priority: 255
2018-01-02 14:31:48.162901-0500 SwiftVoiceCallKitQuickstart[38632:8423627] [VERBOSE Twilio] Inside setCodecPriorities:, codec: speex/8000/1 -> priority: 254
2018-01-02 14:31:48.163335-0500 SwiftVoiceCallKitQuickstart[38632:8423627] [VERBOSE Twilio] Inside setCodecPriorities:, codec: speex/32000/1 -> priority: 0
2018-01-02 14:31:48.163536-0500 SwiftVoiceCallKitQuickstart[38632:8423627] [VERBOSE Twilio] Inside setCodecPriorities:, codec: PCMU/8000/1 -> priority: 128
2018-01-02 14:31:48.163688-0500 SwiftVoiceCallKitQuickstart[38632:8423627] [VERBOSE Twilio] Inside setCodecPriorities:, codec: PCMA/8000/1 -> priority: 0
2018-01-02 14:31:48.165112-0500 SwiftVoiceCallKitQuickstart[38632:8423627] [INFO Twilio] recreateMainTransport, Found valid IPv4 address: 192.168.1.7
2018-01-02 14:31:48.166711-0500 SwiftVoiceCallKitQuickstart[38632:8423627] [DEBUG TVOConstants] X-Twilio-Client string: {"p":"ios","v":"2.0.0","mobile":{"arch":"i386","product":"iPhone","name":"x86_64","v":"11.2"}}, inside TVOConstants clientString
2018-01-02 14:31:48.178436-0500 SwiftVoiceCallKitQuickstart[38632:8423627] [DEBUG TVOReachability] Reachability Flag Status: -R ------- networkStatusForFlags
2018-01-02 14:31:48.178735-0500 SwiftVoiceCallKitQuickstart[38632:8423627] [DEBUG TVOCommandHandler] Inside postCommand:, received command of type TVOMakeCallCommand
2018-01-02 14:31:48.178999-0500 SwiftVoiceCallKitQuickstart[38632:8424532] [VERBOSE Twilio] Inside constructUri: Registration URL: sip:None@chunderm.gll.twilio.com;transport=tls
2018-01-02 14:31:48.179136-0500 SwiftVoiceCallKitQuickstart[38632:8424532] [INFO TVOMakeCallCommand] Call URI: sip:None@chunderm.gll.twilio.com;transport=tls
2018-01-02 14:31:48.179536-0500 SwiftVoiceCallKitQuickstart[38632:8423627] provider:didActivateAudioSession:
2018-01-02 14:31:48.179665-0500 SwiftVoiceCallKitQuickstart[38632:8423627] [VERBOSE TwilioVoice] Enable audio.
2018-01-02 14:31:48.179760-0500 SwiftVoiceCallKitQuickstart[38632:8424532] [VERBOSE TVOCallImpl] Inside makeCall, record permission was granted
2018-01-02 14:31:48.190883-0500 SwiftVoiceCallKitQuickstart[38632:8424532] [DEBUG Twilio] Inside on_call_state(), call: 0x604000130b80, internal state: 1
2018-01-02 14:31:48.191067-0500 SwiftVoiceCallKitQuickstart[38632:8424532] [VERBOSE Twilio] Inside on_call_state(), PJSIP_INV_STATE_CALLING
2018-01-02 14:31:48.191218-0500 SwiftVoiceCallKitQuickstart[38632:8424532] [VERBOSE TVOCall] handlePJSIPInviteStateCalling. Error: (null)
2018-01-02 14:31:48.191484-0500 SwiftVoiceCallKitQuickstart[38632:8424532] [VERBOSE Twilio] on_call_tsx_state(), state: 1, status_code: 0: (null)
2018-01-02 14:31:48.307436-0500 SwiftVoiceCallKitQuickstart[38632:8425357] [AudioHAL_Client] AudioHardware.cpp:666:AudioObjectGetPropertyData:  AudioObjectGetPropertyData: no object with given ID 0
2018-01-02 14:31:48.308848-0500 SwiftVoiceCallKitQuickstart[38632:8425354] [DEBUG Twilio] on_transport_state(): 0
2018-01-02 14:31:48.309118-0500 SwiftVoiceCallKitQuickstart[38632:8425354] [DEBUG Twilio] ------>Transport connected: 0xba8efa28, inside transportConnected:
2018-01-02 14:31:48.508948-0500 SwiftVoiceCallKitQuickstart[38632:8424532] [aurioc] 1411: AUIOClient_StartIO failed (-66637)
2018-01-02 14:31:48.509504-0500 SwiftVoiceCallKitQuickstart[38632:8425427] [aurioc] 1707: AURemoteIO@0x7fe4bc0ba040: IOThread exiting with error 0x10004006
2018-01-02 14:31:48.531916-0500 SwiftVoiceCallKitQuickstart[38632:8424532] [aurioc] 1411: AUIOClient_StartIO failed (-66637)
2018-01-02 14:31:48.532326-0500 SwiftVoiceCallKitQuickstart[38632:8425428] [aurioc] 1707: AURemoteIO@0x7fe4bc0ba040: IOThread exiting with error 0x10004006
2018-01-02 14:31:48.555092-0500 SwiftVoiceCallKitQuickstart[38632:8424532] [aurioc] 1411: AUIOClient_StartIO failed (-66637)
2018-01-02 14:31:48.555496-0500 SwiftVoiceCallKitQuickstart[38632:8425429] [aurioc] 1707: AURemoteIO@0x7fe4bc0ba040: IOThread exiting with error 0x10004006
2018-01-02 14:31:48.578414-0500 SwiftVoiceCallKitQuickstart[38632:8424532] [aurioc] 1411: AUIOClient_StartIO failed (-66637)
2018-01-02 14:31:48.578852-0500 SwiftVoiceCallKitQuickstart[38632:8425431] [aurioc] 1707: AURemoteIO@0x7fe4ba8f6a40: IOThread exiting with error 0x10004006
2018-01-02 14:31:48.601539-0500 SwiftVoiceCallKitQuickstart[38632:8424532] [aurioc] 1411: AUIOClient_StartIO failed (-66637)
2018-01-02 14:31:48.601951-0500 SwiftVoiceCallKitQuickstart[38632:8425432] [aurioc] 1707: AURemoteIO@0x7fe4bc0c0040: IOThread exiting with error 0x10004006
2018-01-02 14:31:48.624834-0500 SwiftVoiceCallKitQuickstart[38632:8424532] [aurioc] 1411: AUIOClient_StartIO failed (-66637)
2018-01-02 14:31:48.625247-0500 SwiftVoiceCallKitQuickstart[38632:8425433] [aurioc] 1707: AURemoteIO@0x7fe4bc0ba040: IOThread exiting with error 0x10004006
2018-01-02 14:31:48.627712-0500 SwiftVoiceCallKitQuickstart[38632:8424532] PJSIP(1):    pjsua_aud.c  .Unable to open sound device: Unknown OpenSSL error 503317117 [status=506637]
Assertion failed: (status == PJ_SUCCESS), function +[TwilioVoice enableAudio]_block_invoke, file /Users/ibadmin/jenkins/workspace/voice-ios-snapshot/TwilioVoiceClient/TwilioVoiceClient/Sources/TwilioVoice.mm, line 299.
```

### Versions

8ea0aa0fa012d880bac9dfbf5fb59aadd0f1cee4

#### Voice iOS SDK

2.0.0

#### Xcode

Xcode 9.2

#### iOS Version

iOS 11.2

#### iOS Device

iPhone SE Simulator.
It should be slow. It's hard to reproduce on fast simulator.

**Comment by bchen-twilio** [comment] 2018-01-02 20:35
Hi @Speakus 

Thanks for choosing the Twilio Voice SDK and reporting the issue.
It looks like the SDK is raising a debug assertion due to the failure when trying to start the audio unit. I've tried the same steps myself (iPhone SE simulator, iOS 11.1) but was not able to reproduce the crash though. 

I'll try with Xcode 9.2 and iOS 11.2 again (I am currently using Xcode 9.1 and iOS 11.1) and in the mean time, does this happen on the same computer with other device simulators such as iPhone 5s?

Thanks.
-bobie

**Comment by Speakus** [comment] 2018-01-02 20:58
Hi @bchen-twilio 
I'm able to reproduce the issue on Xcode 9.2 with iphone 5s simulator as well as `Xcode 9.1` with iphone 5s simulator too.
Main idea for 100% reproducing - to have slow computer (in our case just computer with HDD should be fine).

![image](https://user-images.githubusercontent.com/849294/34499796-761ef124-f053-11e7-8be0-7cbef3248649.png)

**Comment by Speakus** [comment] 2018-01-03 16:04
NB! There was no crash on beta21 for same configuration.

**Comment by bchen-twilio** [comment] 2018-01-03 18:47
Hi @Speakus,

Yes, I think that is expected since the assertion was added after that to make sure the audio unit is started properly.
I am curious (if it's not too much trouble for you to try) if the audio is working properly with release configuration, where the assertions are by default skipped by the compiler. Also curious if audio works fine with the same environment but with beta21?

Thanks again for experimenting and providing debugging information with different versions.
-bobie

**Comment by Speakus** [comment] 2018-01-03 23:18
@bchen-twilio crash is still here for release version. (and it is expected cause framework is compiled)
It's not convenient to test on beta21 since app was updated to last version. The issue was reproduced on our app but I have to update voice-quickstart-swift to be sure the issue is here and not inside our code.

I retest it on 6eb3c2400fee43bff4d4c4f74944cb51fec4aeb5 which use beta19 - and it looks like it works without crashes.

But I have found the real(?) root cause of the issue. Our mac mini does not have connected microphone so after connecting microphone to this macmini - the crash goes away.

**Comment by bchen-twilio** [comment] 2018-01-03 23:30
Hi @Speakus 

Yes, the original log message showed that the assertion was raised because the SDK couldn't find the proper audio device to start the audio unit, which should not be the case for actual iDevices.
Thanks for sharing the findings.

**Comment by bchen-twilio** [comment] 2018-01-10 22:10
Hi @Speakus 

I am assuming that the app and the SDK are working great and I'll go ahead and close this ticket for now. Please feel free to open a new ticket if you run into any problem in the future.

Thanks.
-bobie

**Closed by bchen-twilio** 2018-01-10 22:10 UTC

**Comment by Speakus** [comment] 2018-01-10 23:29
hm.. for my opinion this issue has low priority since affect only device with broken microphone but it was not solved. It never happened on old version - and crash does not look as anything applicable.

**Comment by Speakus** [comment] 2018-01-10 23:29
@bchen-twilio

**Comment by bchen-twilio** [comment] 2018-01-10 23:33
@Speakus 
I understand.
We have removed the assertion in the release build which should not cause a hard-stop like you were seeing, and at the same time we added some error handlings and message to help debug the audio issue if it happened.
Let me know if this makes sense.

**Comment by Speakus** [comment] 2018-01-10 23:36
@bchen-twilio yes - this makes sense.
