### ISSUE TITLE
Issue in testing call 

### ISSUE THREAD

**Issue by Hamza123Imran** [twilio/voice-quickstart-swift#164] opened 2018-09-10 07:47 UTC
Hi, i have run this project in my mac, and created backend in php. I have a base URL and and token 
is coming on the URL. Now the number i'm trying to call and mine number are registered on twilio. But when i call it fails the action. This is my credentials , `let baseURLString = "http://softdepth.com/projects/raven/customer/getAudioAccessToken.php"
// If your token server is written in PHP, accessTokenEndpoint needs .php extension at the end. For example : /accessToken.php
let accessTokenEndpoint = "getAudioAccessToken"
let identity = "+923097124818"
let twimlParamTo = "+923244544783"`

Now when this function is call, here is a client parameter which is empty, what we have to write in client? 
`func provider(_ provider: CXProvider, perform action: CXStartCallAction) {
        NSLog("provider:performStartCallAction:")
        
        toggleUIState(isEnabled: false, showCallControl: false)
        startSpin()

        TwilioVoice.configureAudioSession()
        TwilioVoice.isAudioEnabled = false
        
        provider.reportOutgoingCall(with: action.callUUID, startedConnectingAt: Date())
        
        self.performVoiceCall(uuid: action.callUUID, client: "") { (success) in
            if (success) {
                provider.reportOutgoingCall(with: action.callUUID, connectedAt: Date())
                action.fulfill()
            } else {
                action.fail()
            }
        }
    }`
In this delegate my action fails. and what is client parameter for?

**Comment by bchen-twilio** [comment] 2018-09-10 18:55
Hi @Hamza123Imran 

Sorry for the confusion but the `client` parameter here is for the `performVoiceCall()` method to pass as part of the `params` parameter so that the server (in this case the PHP endpoint) can pick up and generate TwiML response.

Did you see any error message when the action failed or did you get the `!success` route inside the completion block of `performVoiceCall()`?

**Comment by Hamza123Imran** [comment] 2018-09-11 08:28
Hi, i have run the code, now when i run the app i got an audio call which says sorry for error message you are using demo account, call fails. I want to confirm that when i purchase my account and create credentials again for my server than it will make call fine?

**Comment by bchen-twilio** [comment] 2018-09-11 16:57
Hi @Hamza123Imran 

I believe that you were seeing the message because the balance of the account is out. You can provide new payment methods in your account settings and rest assured you can definitely continue with all the account credentials and applications you have already set up.

cheers
-bobie

**Comment by Hamza123Imran** [comment] 2018-09-11 17:05
Hi, i have purchased new account and created new credentials and Push credentials for my app, Now when i make a call i get ringing text in my console and it Successfully registered for VoIP push notifications. but after that it moves to the call fail with localization error and audio is disable . Now how can i make the call? Why this error is now shown?

**Comment by bchen-twilio** [comment] 2018-09-11 17:09
Hi @Hamza123Imran 

Please provide us the error message so we can further investigate. It would also be great if you can provide us the Call SID associated with the failed call. You should be able to find the Call SIDs in your [Voice Dashboard](https://www.twilio.com/console/voice/dashboard).

**Comment by Hamza123Imran** [comment] 2018-09-11 17:16
This is the delegate method where my app comes at and fail the call
`func call(_ call: TVOCall, didFailToConnectWithError error: Error) {
        NSLog("Call failed to connect: \(error.localizedDescription)")
        
        if let completion = self.callKitCompletionCallback {
            completion(false)
        }
        
        performEndCallAction(uuid: call.uuid)
        callDisconnected()
    }`

**Comment by bchen-twilio** [comment] 2018-09-11 17:18
And did you see any error message in your Xcode debug console?

**Comment by Hamza123Imran** [comment] 2018-09-11 17:21
Yup, this is what it prints in console, `Call failed to connect: Connection error (603).` and this `EndCallAction transaction request failed: The operation couldn’t be completed. (com.apple.CallKit.error.requesttransaction error 4.).`

**Comment by Hamza123Imran** [comment] 2018-09-11 17:34
First of all when i open my VC , it call this delegate for push credentials,
`func pushRegistry(_ registry: PKPushRegistry, didUpdate credentials: PKPushCredentials, for type: PKPushType) { }` , its prints all the registered number that are on my twilio account. Then i make a call, it shows this as udid `1D6C8A16-C58D-4975-9697-DB2E2FD13CC0`. I'm making call from my number to another number . The other number is registered on twilio as well

**Comment by Hamza123Imran** [comment] 2018-09-11 17:51
In identity i'm passing my number and in to i'm passing the other user number.

**Comment by bchen-twilio** [comment] 2018-09-12 18:32
Hi @Hamza123Imran 
I'll reply the call failure in #165.
When you receive the incoming call notification and attempt to accept the call, are you able to connect the call?

**Comment by bchen-twilio** [comment] 2019-04-02 00:52
Closing this issue for now. @Hamza123Imran Please feel free to re-open if you believe the issue is still happening.
Thanks,
-bobie

**Closed by bchen-twilio** 2019-04-02 00:52 UTC
Labels: help wanted
