### ISSUE TITLE
I can't receive an incoming call

### ISSUE THREAD

**Issue by jannomeister** [twilio/voice-quickstart-swift#207] opened 2019-02-05 01:32 UTC
I followed all the steps for ios from generating [Create VoIP Service Certificate](https://github.com/twilio/voice-quickstart-swift#bullet7) to  [Create a Push Credential with your VoIP Service Certificate](https://github.com/twilio/voice-quickstart-swift#bullet8)

I get the outcoming call successfully working, but not the incoming call. I can't receive push notification/voip notification. I enable it on xcode, created certificates, added the values of `cert.pem` and `key.pem` to twilio. And I got the error https://www.twilio.com/docs/api/errors/52143

**Comment by ramohanreddy** [comment] 2019-02-05 09:53
Hi @jannomeister 
can u share me getting voip notification code if it possible

**Comment by bchen-twilio** [comment] 2019-02-05 18:01
Hi @jannomeister 

I am sorry that you are experiencing problem integrating the SDK to enable incoming capability. Please file a [Twilio Support](https://support.twilio.com/hc/en-us) ticket with your Account SID and Call SID of the problematic call if possible (note: PLEASE DO NOT disclose any account credentials here publicly).

Couple of questions:
- Are you able to call `TwilioVoice.register()` and register successfully (most likely this is not the problem, but just asking)
- What does the 52143 error say when you click the links in the [Programmable Voice Dashboard](https://www.twilio.com/console/voice/dashboard)? Usually it gives some details as of the reason why the notification delivery failed.

Thanks
-bobie

**Comment by ramohanreddy** [comment] 2019-02-14 07:54
hi @bchen-twilio 
I am not able get incoming call notification.

**Comment by bchen-twilio** [comment] 2019-02-14 17:49
Hi @ramohanreddy 

Please provide a Call SID which you were not able to receive incoming call notification.

Thanks

**Comment by bchen-twilio** [comment] 2019-04-02 00:32
Closing this issue for now assuming the issue has been resolved.
@ramohanreddy please feel free to reopen the issue if the problem is still happening on your end, and would be great if you can also provide Call SID of the call where the callee is not getting notification.

Thanks,
-bobie

**Closed by bchen-twilio** 2019-04-02 00:32 UTC
