### ISSUE TITLE
CallKit Incoming call UI not showing up occasionally

### ISSUE THREAD

**Issue by ojhakapil** [twilio/voice-quickstart-swift#158] opened 2018-08-17 13:48 UTC
Hello Twilio Support,

I'm facing an issue in which CallKit is not showing up the incoming call UI when there is an incoming VoIP call. This mostly happens when the app is either in background and/or device is locked and put in background for 5-10 minutes. 

I've referenced the TwilioVoiceCallKitQuickStart source code.

I'm using TwilioVoice 2.0.4.

Thanks

**Comment by bchen-twilio** [comment] 2018-08-17 17:15
This looks like a duplicate of #152. Closing this one.
@ojhakapil quick solution: in the PushKit `didReceiveIncomingPushWith` callback, dispatch the completion to the main queue and see if this solves the issue
```
  DispatchQueue.main.async {
    completion()
  }
```

**Closed by bchen-twilio** 2018-08-17 17:15 UTC

**Comment by ashish001-App** [comment] 2021-06-29 03:41
This is not working

**Comment by bobiechen-twilio** [comment] 2021-06-29 15:42
@ashish001-App 

Can you share more details about the exact issue you are facing? I am assuming your application is not showing incoming calls properly when the app is not active - please make sure that the application implements the PKPushRegistry instance at app launch like the [quickstart AppDelegate example](https://github.com/twilio/voice-quickstart-ios/blob/master/SwiftVoiceQuickstart/AppDelegate.swift).
