### ISSUE TITLE
iOS SDK 3.0.0-preview2 uploads to App Store problem

### ISSUE THREAD

**Issue by jessicawang143143** [twilio/voice-quickstart-swift#163] opened 2018-08-30 03:28 UTC
### Description

I upgraded twilio sdk to 3.0.0-preview2. Everything worked fine until I tried to upload new build to App Store. I got two issues and kind of fixed the first one. I put the first one here as well for you might want to know.

First issue: is fixed after I delete file 'inject_credentials.sh'
￼
![734d30d4-d7a4-4b40-8b83-c0106eadfea8](https://user-images.githubusercontent.com/23222136/44827773-c2d33d00-ac68-11e8-8c51-bacc32d3b5ad.png)

Second issue: currently I am stuck here 
<img width="659" alt="ad9f9ecf-ab6e-4970-9479-6d75d0ce8632" src="https://user-images.githubusercontent.com/23222136/44827782-c9fa4b00-ac68-11e8-93af-69aa8c98adef.png">

Since I don't have camera usage in app , I tried to use twilio 2.0.6 to upload again and it worked. 
I think it might be related to WebRTC, which has possibilities to ask permissions for Microphone or Camera. 
Do you mind check that?

### Steps to Reproduce

1. Update twilio version in pod file and update pod 
2. Change all the related api changes
3. Archive and upload to App Store 

### Versions

3.0.0-preview2 (August 28, 2018)

#### Xcode

Version 9.4.1 (9F2000)

**Comment by piyushtank** [comment] 2018-08-30 04:28
@jessicawang143143 Thank for reaching out. Yes, the the WebRTC library used by the 3.0.0-preview2 Voice SDK has Audio+Video both in it, and thats probably the reason why you are running into this issue. I apologize for the inconvenience.  

We are working on building the Voice SDK with audio only variant of WebRTC where you should not see this problem. We aim to ship this fix in a few days. I will let you know when it is released.

Best,
Piyush

**Comment by bchen-twilio** [comment] 2018-09-11 01:42
Hi @jessicawang143143 

Just writing to let you know that we are actively working on fixing the issue. `CLIENT-5121` is the number for tracking the issue.

Thanks
-bobie

**Comment by bchen-twilio** [comment] 2018-09-13 21:18
Hi @jessicawang143143 

We've just finished the release of 3.0.0-preview3 ([changelog](https://www.twilio.com/docs/voice/voip-sdk/ios/3x-changelog#300-preview3-september-12-2018)).

Although the fix for `CLIENT-5121` is not included in this version, we've actually made some good progress of building audio-only variant of WebRTC library (kudos to @piyushtank) so that it no longer requires video related dependencies. We've also used the library and uploaded the application to the store and confirmed that the auto-validation system does not complain about `NSCameraUsageDescription` being missed in the plist.

Anyway, the `inject_credentials.sh` file has been removed from the framework bundle in preview2.

Thanks again for reporting the issue and we hope to get back to you with new updates.
-bobie

**Comment by maxannear** [comment] 2018-09-14 02:14
Appreciate the hard work @bchen-twilio and @piyushtank. Exciting you've got it up to v67 of WebRTC

Looking forward to using it with our beta test group once its audio-only!

**Comment by bchen-twilio** [comment] 2018-10-02 23:20
Hi everyone,

We've just release the Voice iOS SDK 3.0.0-preview4 ([changelog](https://www.twilio.com/docs/voice/voip-sdk/ios/3x-changelog#300-preview4-october-2-2018)), which has the audio-only WebRTC and should no longer cause this issue when the app is uploaded or submitted for review. Please update and let us know how it goes.

Thanks!
-bobie

**Comment by jessicawang143143** [comment] 2018-10-03 03:08
Thank you for keep us updated about you progress. I will upgrade to preview4 and try to upload again.

**Comment by maxannear** [comment] 2018-10-09 23:53
Thanks @bchen-twilio and @piyushtank. Its now working for us and we're testing it with our beta test group.

**Comment by bchen-twilio** [comment] 2018-12-29 00:47
Closing issue and since the original issue has been resolved.

**Closed by bchen-twilio** 2018-12-29 00:47 UTC
Labels: bug
