### ISSUE TITLE
Incoming call not getting transferred to bluetooth headset

### ISSUE THREAD

**Issue by ojhakapil** [twilio/voice-quickstart-swift#135] opened 2018-05-24 05:07 UTC
Hello Twilio Support,

I have recently integrated CallKit support in my Twilio VoIP app by referencing TwilioVoiceCallKitQuickStart github repo. 

I have connected my device with bluetooth headsets so all audio should be routed to the headset. But when I'm receiving an incoming call, the call is routed to the iPhone instead of the headset, I'm unable to hear anything on the headsets.

Here are more details:

TwilioVoice sdk version: 2.0.4
Device: iPhone X
iOS Version: 11.2.5

Thanks

**Comment by bchen-twilio** [comment] 2018-05-24 05:10
Hi @ojhakapil 

I guess you answered the CallKit call from the phone UI, right? Try answer the incoming call via the answer button on the bluetooth headset and audio should be routed to the headset. This is an expected behavior by Apple.

**Comment by ojhakapil** [comment] 2018-05-24 05:55
Hi @bchen-twilio 

You are right. I was answering the call from the phone UI rather than the answer button on my bluetooth headset.

Thanks so much for your quick response. I appreciate it.

**Comment by bchen-twilio** [comment] 2018-05-24 16:54
You are most welcome! I actually found this "behavior" while answering calls in my car.
In case you answer the call from phone UI instead of the bluetooth headset, you can still switch the audio route in the native phone app UI.

I am closing this ticket but as always, feel free to reach out to us if you run into any issue/question.

**Closed by bchen-twilio** 2018-05-24 16:54 UTC

**Comment by chetan1406** [comment] 2023-04-12 06:55
Hello @bobiechen-twilio 
        
            Using Twilio since 2019 working fine with SDK 5.5.1 but incoming calls stops on that so I integrated SDK 6.1.0 and now facing a headset issue.

Here are more details:

TwilioVoice SDK version: 6.1.0
Device: iPhone XS
iOS Version: 16.4
