### ISSUE TITLE
App doesn't build

### ISSUE THREAD

**Issue by mattwritescode** [twilio/voice-quickstart-swift#6] opened 2016-10-24 16:56 UTC
After cloning and running pod install, the app starts off with 8 errors. This may have more to do with the Cocoapod set up for TwilioVoiceClient (2.0.0-beta4).

Here's the errors I'm getting (I've included a screenshot below for better readability):

SwiftVoiceQuickstart Group
Swift Compiler Error Group
/Users/matthewbtyler/Documents/4DK/GitHub/voice-quickstart-swift/SwiftVoiceQuickstart/ViewController.swift:13:21: Editor placeholder in source file
/Users/matthewbtyler/Documents/4DK/GitHub/voice-quickstart-swift/Pods/TwilioVoiceClient/TwilioVoiceClient.framework/Headers/TwilioVoiceClient.h:17:9: Include of non-modular header inside framework module 'TwilioVoiceClient'
/Users/matthewbtyler/Documents/4DK/GitHub/voice-quickstart-swift/Pods/TwilioVoiceClient/TwilioVoiceClient.framework/Headers/TwilioVoiceClient.h:19:9: Include of non-modular header inside framework module 'TwilioVoiceClient'
/Users/matthewbtyler/Documents/4DK/GitHub/voice-quickstart-swift/Pods/TwilioVoiceClient/TwilioVoiceClient.framework/Headers/TwilioVoiceClient.h:21:9: Include of non-modular header inside framework module 'TwilioVoiceClient'
/Users/matthewbtyler/Documents/4DK/GitHub/voice-quickstart-swift/Pods/TwilioVoiceClient/TwilioVoiceClient.framework/Headers/TwilioVoiceClient.h:22:9: Include of non-modular header inside framework module 'TwilioVoiceClient'
/Users/matthewbtyler/Documents/4DK/GitHub/voice-quickstart-swift/Pods/TwilioVoiceClient/TwilioVoiceClient.framework/Headers/TwilioVoiceClient.h:24:9: Include of non-modular header inside framework module 'TwilioVoiceClient'
/Users/matthewbtyler/Documents/4DK/GitHub/voice-quickstart-swift/Pods/TwilioVoiceClient/TwilioVoiceClient.framework/Headers/TwilioVoiceClient.h:25:9: Include of non-modular header inside framework module 'TwilioVoiceClient'
/Users/matthewbtyler/Documents/4DK/GitHub/voice-quickstart-swift/SwiftVoiceQuickstart/ViewController.swift:11:8: Could not build Objective-C module 'TwilioVoiceClient'

<img width="246" alt="screen shot 2016-10-24 at 11 53 17 am" src="https://cloud.githubusercontent.com/assets/4481604/19655217/e0cf6c3a-99e0-11e6-942e-58ae9e1b6726.png">

**Comment by bchen-twilio** [comment] 2016-10-24 18:06
Hey @mattwritescode,

Bobie here from the iOS SDK team. We are sorry that you are experiencing this compiling errors.
The team actually did see this error before but couldn't reproduce it since.
I did a little bit search and found that there are also people having the same trouble when building with Cocoapods + Swift. It looks like the SDK team can actually try and do something to help get rid of this problem once and for all.

My Xcode is `Version 8.0 (8A218a)` and I tried both Cocoapods `1.0.1` and `1.1.1` but couldn't reproduce the compile error using the SwiftVoiceQuickstart sample app. Could you provide us some more details about your development environment, like the versions of  Xcode and Cocoapods library? Thanks!

**Comment by mattwritescode** [comment] 2016-10-25 15:29
Xcode Version 8.0 (8A218a)
Cocoapods 1.0.0.beta.5

**Comment by bchen-twilio** [comment] 2016-10-25 18:52
Hi @mattwritescode,
Thanks for getting back with the versions.
I tried to install Cocoapods `1.0.0.beta.5` on my machine and the Swift quickstart, and I was able to confirm that I experienced the same compile error when using Cocoapods 1.0.0.beta.5 and the problem went away if I switched to the latest 1.1.1 Cocoapods library.
Could you help us upgrade the Cocoapods library on your machine and give it a try again?
Thanks!

**Comment by mattwritescode** [comment] 2016-10-25 19:31
That fixed it. Thanks!

**Comment by bchen-twilio** [comment] 2016-10-25 19:52
Cool @mattwritescode! Glad to hear that.
I will close this issue but please feel free to let us know if you run into any issue with the Voice SDK.

**Closed** 2016-12-01 01:17 UTC
