### ISSUE TITLE
Call notifications stop when app is in background - Can't end BackgroundTask: no background task exists with identifier

### ISSUE THREAD

**Issue by jbrooksga** [twilio/voice-quickstart-swift#269] opened 2019-10-02 20:12 UTC
Hello,

Running the following:

- SDK 5.0
- Xcode 11
- iOS 13.1.2 (also happened with 13.1.1)
- iPhone 7 Plus

Problem: When the app is sent to background or closed, incoming calls do not arrive at all. If the app ls brought back to the foreground, calls work correctly. Problem does not exist with iOS 12.4

The debug content is: 
Can't end BackgroundTask: no background task exists with identifier 1 (0x1), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug. 

Note that all we see is this debug message, as the app will not crash when in debug mode. 

Steps to reproduce:
Launch app, return to iPhone home screen
OR
Keep app closed

**Comment by bchen-twilio** [comment] 2019-10-02 20:19
Hi @jbrooksga 

I just tried the Swift quickstart and was able to see the incoming call notification while app was not in the foreground (backgrounded/terminated/device locked). Is this happening in your environment with the latest Swift quickstart?

Thanks,
-bobie

**Comment by jbrooksga** [comment] 2019-10-02 20:26
Bobie,

Thanks for the quick reply.

My app was developed on an earlier version of the quickstart. That said I went though great effort to make sure all of the recent pull requests were reviewed and added to my code. There certainly could be some other elements in my app contributing to this issue.

Just curious, in your test above did you happen to see the BackgroundTask message in the debug when the app is goes to the background?

**Comment by bchen-twilio** [comment] 2019-10-02 20:39
Thanks for the update @jbrooksga.
Yes, I do see the same background task related message in the debugging console. We need to investigate if that's caused by the SDK but I've checked my devices and was only seeing the message on iOS 13. No such message when running the app on iOS 12.4 device. (Both using Xcode 11)

-bobie

**Comment by jbrooksga** [comment] 2019-10-02 20:41
No such message when running the app on iOS 12.4 device. (Both using Xcode 11)
> 
> -bobie

Correct....same observation here.

**Comment by jbrooksga** [comment] 2019-10-02 20:42
Could the inbound call failure I'm seeing be related to this:

> https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns
apns-push-type
(Required when delivering notifications to devices running iOS 13 and later, or watchOS 6 and later. Ignored on earlier system versions.) The type of the notification. The value of this header is alert or background. Specify alert when the delivery of your notification displays an alert, plays a sound, or badges your app's icon. Specify background for silent notifications that do not interact with the user.

**Comment by bchen-twilio** [comment] 2019-10-02 20:50
Hi @jbrooksga 

Twilio does specify the `apns-push-type` attribute when requesting the notification deliveries to Apple and we have verified that the flag works on both iOS 13 and previous versions. One potential area I can think of is how the completion handler of the PushKit incoming-push callback is fulfilled ([sample code](https://github.com/twilio/voice-quickstart-swift/blob/master/SwiftVoiceQuickstart/ViewController.swift#L284)) and when the app reports the VoIP to CallKit.

-bobie

**Comment by jbrooksga** [comment] 2019-10-02 21:12
Thank you for that specific code reference.

Appears there were some recent code changes for ios13 here I might have missed. I'll investigate and report back.

**Comment by jbrooksga** [comment] 2019-10-02 21:55
As a quick test I just used the full callInviteReceived function verbatim in the latest Quickstart. No change in the result so the issue is not within that function.

**Comment by jbrooksga** [comment] 2019-10-02 23:49
The interesting situation is that following the same procedure to produce the error, in Debug the app does not crash. However in Test Flight we get a crash.

**Comment by bchen-twilio** [comment] 2019-10-03 00:12
Hi @jbrooksga 

This sounds bad. Would be interested in learning the details of the crash.

**Comment by jbrooksga** [comment] 2019-10-03 15:34
This is getting more clear as I move deeper into the investigation. My app does something rather unique over and above the Quickstart. In certain instances, I will redirect the call to another URL instead of it being presented to the iOS client. I have now reached the point where the app WILL crash in Debug.

The procedure to reproduce is the same. When a call invite is received that is to be redirected, my code does the redirect, BUT this is what now occurs:

2019-10-03 11:21:35.998915-0400 MyVOIPAPP[1074:316284] Apps receving VoIP pushes must post an incoming call (via CallKit or IncomingCallNotifications) in the same run loop as   pushRegistry:didReceiveIncomingPushWithPayload:forType:[withCompletionHandler:] without delay.
2019-10-03 11:21:35.999087-0400 MyVOIPAPP[1074:316284] *** Assertion failure in -[PKPushRegistry _terminateAppIfThereAreUnhandledVoIPPushes], /BuildRoot/Library/Caches/com.apple.xbs/Sources/PushKit/PushKit-36/PKPushRegistry.m:343
2019-10-03 11:21:35.999544-0400 MyVOIPAPP[1074:316284] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Killing app because it never posted an incoming call to the system after receiving a PushKit VoIP push callback.'
*** First throw call stack:
(0x1b276498c 0x1b248d0a4 0x1b2666d1c 0x1b2a9c8f4 0x1c6265a5c 0x103edec04 0x103eed888 0x1c62649cc 0x103edd828 0x103edec04 0x103eecc64 0x1b26e23c4 0x1b26dd3b8 0x1b26dc8bc 0x1bc548328 0x1b67726d4 0x100494c30 0x1b2567460)
libc++abi.dylib: terminating with uncaught exception of type NSException

I think we know the reason this is happening. 

Will these procedures fulfill the PushKit requirement for reporting the call which was redirected?

 ```
reportIncomingCall(from: remoteCallNumber!, uuid: uuid)

                DispatchQueue.main.async {
                    self.performEndCallAction(uuid: self.callInvite!.uuid)
                }
```

**Comment by bchen-twilio** [comment] 2019-10-03 16:44
Hi @jbrooksga 

Thanks for the update. Indeed this could violate the new PushKit policy although the workaround seems to avoid the exception, we still recommend applications to always report new incoming calls to CallKit when VoIP notifications are received to avoid incoming call capability being compromised or rejection during store submission.

It seems the issue has been identified and the workaround does resolve the scenario, I will close this ticket for now but please feel free to reach out to us if you run into any issues.

Thanks again,
-bobie

**Closed by bchen-twilio** 2019-10-03 16:44 UTC
