### ISSUE TITLE
When call has been hung up not from app, callkit is still running

### ISSUE THREAD

**Issue by jaelee1993** [twilio/voice-quickstart-swift#190] opened 2018-11-09 14:34 UTC
Hey guys,
So I realized that when someone who I am talking to hang up before I do from the app CallKit is still running in the back. I guess CallKit isn't being notified that Twilio has been disconnected so its still running in the background. Is there a way around this?
Thank you

**Comment by bchen-twilio** [comment] 2018-11-09 17:48
Hi @jaelee1993 

Thanks for reporting the issue.
When you observed that the CallKit call was not properly terminated, were you able to see any CallKit request error or Voice SDK error in the debugger?

-bobie

**Comment by jaelee1993** [comment] 2018-11-12 14:01
@bchen-twilio Thank you getting back to me. 
So I don't think there was an error, however CallKit was continuously running in the back ground. The only way to kill it was to close my app.


`func call(_ call: TVOCall, didDisconnectWithError error: Error?) {
        if let error = error {
            NSLog("Call failed: \(error.localizedDescription)")
        } else {
            NSLog("Call disconnected")
            performEndCallAction(uuid: self.call!.uuid)  <---Added here

        }
        
        callDisconnected()
    }`


I added the performEndCallAction in the function above and seemed to resolve the issue.

**Comment by bchen-twilio** [comment] 2018-11-12 17:52
Hi @jaelee1993 

Actually right after I replied last week we realized this is actually a regression caused by [this PR](https://github.com/twilio/voice-quickstart-swift/pull/171). We will update the Voice quickstart to address this issue but you can try the fix in the [Video iOS quickstart PR](https://github.com/twilio/video-quickstart-swift/pull/327).

Sorry for the inconvenience.
Thanks
-bobie

**Comment by bchen-twilio** [comment] 2018-12-29 00:35
Hi @jaelee1993 

We have updated the sample apps recently to address the issue. I am closing the issue but please feel free to reopen if you believe the issue still exists with the fixes or open a new issue if you run into any problems.

Thanks
-bobie

**Closed by bchen-twilio** 2018-12-29 00:35 UTC
Labels: help wanted
